### ISSUE TITLE
Default resolution with no monitor causes problems with large windows

### ISSUE THREAD

**Issue by sconemad** [RealVNC/raspi-preview#1]
With VNC Server, you are able to view the Pi's display output even when there is no monitor attached to the Pi itself. However, the screen resolution chosen by default is very low (720x480 pixels), which can cause problems when viewing large windows or dialog boxes as they may not fit entirely on the screen.

This is a problem for many applications, for example the LXDE desktop's Appearance Settings dialog, and VNC Server's Options dialog (shown below):

![image](https://cloud.githubusercontent.com/assets/2833067/14854287/10316740-0c87-11e6-9e6e-9e034921adfe.png)

Some dialog boxes (such as the VNC Server Options dialog) can be maximized to fit to the available screen space. This can be done in several ways, for example, clicking on the visible part of the task bar at the top of the screen, right-clicking on the "VNC Server - Options" entry in the task list, and selecting "Maximize".

Other dialogs may not support this. If this is the case, you can still move them around by clicking and dragging the window with the Alt key held down. However, to do this via VNC, you need to use the F8 menu and select Alt (which effectively presses the Alt key on the Server), then you can click and drag anywhere in the window to move it around, remembering to deselect Alt from the F8 menu when you're done. Otherwise, you'll likely be moving the VNC Viewer window!

To avoid these kinds of problems, we recommend that you increase the screen resolution for your Raspberry Pi if you are using it with no monitor attached. To do this, you need to edit the /boot/config.txt file on your device - see [this page](https://www.raspberrypi.org/documentation/configuration/config-txt.md) for more information.

For example, the following settings will set the display to 1080p (1920x1080 pixels):

```
disable_overscan=1
hdmi_force_hotplug=1
hdmi_group=1
hdmi_mode=16
```

**Comment by Saijin-Naib** [comment]
Is it possible to have the RealVNC server handle this more elegantly like xRDP does?

I have my Pi semi-headless, where I have the WaveShare SpotPear 3.2" LCD attached via GPIO, and I have the mode set to drive that display at 320x240.

Under xRDP, the client (my desktop) requests and receives its native display resolution of 1080p without my intervention. This is desirable behavior, in my opinion.

**Comment by sconemad** [comment]
Hi Saijin-Naib,

It's possible to set the desktop geometry in our virtual mode server (started via vncserver). See the documentation for the "randr" parameter here:
https://www.realvnc.com/products/vnc/documentation/5.3/parameters/vncserver.html
This allows you to set a list of geometries which you can switch between.

**Comment by Saijin-Naib** [comment]
Hey,
I'm aware that you can force a resolution manually, but I'm referring to the capability of dynamic/intelligent resolution setting via a request by the connecting client to the server. This is a much better behavior.

**Comment by Ruffio** [comment]
Has this issue been resolved or should it be closed?

**Comment by minkustree** [comment]
The preview has now ended, and a full version of the software is included with Raspbian and available from https://realvnc.com. We will unfortunately not be making any further comments on issues reported here.
