### ISSUE TITLE
Will There Be An Update Before Jan 2017?

### ISSUE THREAD

**Issue by opticyclic** [RealVNC/raspi-preview#10]
According to the README, the licence expires at the end of Jan 2017.
There have been no update since the initial drop 7 months ago.
Will there be an update before the end of the licence period?

**Comment by sconemad** [comment]
Hi,

Tthe version of VNC Server on this repo is an alpha version that we made available for people to try out prior to the official release. This has actually now been released, and is available to download from our website here: https://www.realvnc.com/docs/raspberry-pi.html

Or, if you have the latest version of Raspbian Pixel, it is included by default, and the VNC Server can be enabled via the Raspberry Pi configuration app (or raspi-config on the command line).

Sorry for the confusion.

**Comment by sconemad** [comment]
I've added a note to the README for this repo pointing to the stable version on our website.
