### ISSUE TITLE
What login details to use?

### ISSUE THREAD

**Issue by KarelPeeters** [RealVNC/raspi-preview#11]
I'm trying to get RealVNC to work between my laptop and I raspberry pi zero. I am following [this youtube tutorial](https://www.youtube.com/watch?v=4gLzJGrkfVw).

I have installed this version of RealVNC on my RPi and I have installed the windows version on my laptop. I ran vncserver on the RPi:
![starting vncserver](http://i.imgur.com/FsL3Aw3.png)

And then I start VNC Viewer on my pc, I copy the ip address over and I press enter:
![starting VNC Viewer](http://i.imgur.com/h9vyDtE.png)

A dialog opens up that asks me to login. What do I have to fill in here? The combinations I already tried are:

Username | Password
------------ | -------------
[my Windows user name] | [my Windows user password]
pi | raspberry
raspberrypi | raspberry
[my RealVNC account name] | [my RealVNC account password]
<empty> | raspberry

That last one is what I assume he does in the video:
![video typing in password](http://i.imgur.com/ieGcVk2.png)

But all of those failed with `Either the username was not recognised, or the password was incorrect`. Is there anything I'm doing wrong? It is strange to me that I don't have to login on the RPi to my RealVNC account, but I assume that's normal?

**Comment by sconemad** [comment]
Hi, you should use:

username: pi
password: raspberry

By default, unless you've changed these, or configured anything different.

BTW, that YouTube tutorial is now a bit out of date. I'd recommend you install the released version of VNC Server 5.3.2 for the raspberry pi, from the RealVNC website (it's also included in the latest version of raspbian), then you should no longer need to make any parameter changes on the viewer.
