### ISSUE TITLE
No display when used through KANO Os

### ISSUE THREAD

**Issue by wizofe** [RealVNC/raspi-preview#13]
Unfortunately, RealVNC doesn't display anything on the screen when used through [KANO OS](http://www.kano.me).

Kano OS is currently using the Qt Framework to create a layered desktop, resulting in the display of only the Desktop Wallpaper from RealVNC and no other layer on it.

You can try with the latest image here [Kanux 3.14b](http://dev.kano.me/public/4G/img/en_US/Kanux-Beta-v3.14.1-Lovelace-jessie-release.img.gz).

**Comment by drghughes** [comment]
If you need support, please go to https://www.realvnc.com/en/connect/docs/faq/

This project was only used when the Raspberry Pi version of RealVNC was in beta.  Now that it's been released, you need to go to the RealVNC web site to get support.

**Comment by minkustree** [comment]
This preview has now ended, and a full product is included with the latest versions of Raspbian. For support, please follow the advice above.
