### ISSUE TITLE
Kodi not accepting input via VNC when started from the desktop

### ISSUE THREAD

**Issue by sconemad** [RealVNC/raspi-preview#2]
When starting the Kodi Media Center from an X11 desktop, keyboard input via VNC does not work.
Pointer input will work if "Relative Pointer Motion" is enabled from VNC's F8 menu.

You can workaround this issue by booting to the console and starting kodi from there. Keyboard and pointer input should then work as expected.

**Comment by ghost** [comment]
Same problem here. No input from the keyboard on Kodi.
- Raspberry pi 3
- Raspbian 2016-05-27-raspbian-jessie
- Kodi 16.1 (same problem with Kodi v15)
- VNC-Server-5.3.1-raspi-alpha1
- RealVNC 5.3.2 for Windows
- Windows 10 Pro x64

Thanks for the great realease BTW.

**Comment by Ruffio** [comment]
Has this issue been resolved or should it be closed?

**Comment by yugansh20** [comment]
Hi

I am facing same issue.
With almost same config.

**Comment by evil-cartman** [comment]
Same problem here. Nothing?

Is it a VNC, kodi or Pi issue?

**Comment by drghughes** [comment]
Now that RealVNC for Raspberry Pi is out of preview https://www.raspberrypi.org/blog/get-back-to-my-pi-from-anywhere-with-vnc-connect/ you're better off trying to get support from the RealVNC site:  https://www.realvnc.com/en/raspberrypi/ or https://www.realvnc.com/en/connect/docs/faq/ or on the Raspberry Pi site https://www.raspberrypi.org/forums/

**Comment by minkustree** [comment]
The preview has now ended, and a full version of the software is included with Raspbian and available from https://realvnc.com. We will unfortunately not be making any further comments on issues reported here.
