### ISSUE TITLE
VNC Server will not work if GPU memory set too low

### ISSUE THREAD

**Issue by sconemad** [RealVNC/raspi-preview#3]
VNC Server uses the Raspberry Pi's GPU to perform screen capture and optimized encoding, which can fail if the GPU does not have enough memory available to it.

The amount of memory available to the GPU can be configured via the raspi-config program, or by setting the gpu_mem option in /boot/config.txt - see [this page](https://www.raspberrypi.org/documentation/configuration/config-txt.md) for details. 

The default value is 64MB, which is fine in most cases, but the actual value required depends on a number of factors, such as the screen resolution, and running other applications which use the GPU (e.g. Minecraft).

At the moment, VNC Server doesn't handle this situation very well, so we're working on ways to improve this and provide some more useful feedback. You'll currently see something like this if you attempt to connect to a VNC Server running on a device which doesn't have enough GPU memory:

![image](https://cloud.githubusercontent.com/assets/2833067/14882690/cf5a0776-0d31-11e6-98f0-fbe216fd5fee.png)

If this happens, please try setting your GPU memory to 128MB via raspi-config, and try again.

Similarly, if you _are_ able to connect via VNC, but you find that applications requiring the GPU aren't working (e.g. Minecraft), then you may also need to increase your GPU memory.

**Comment by Ruffio** [comment]
Has this issue been resolved or should it be closed?

**Comment by minkustree** [comment]
The preview has now ended, and a full version of the software is included with Raspbian and available from https://realvnc.com. We will unfortunately not be making any further comments on issues reported here.
