### ISSUE TITLE
Failed writing body

### ISSUE THREAD

**Issue by Mike-TB** [RealVNC/raspi-preview#9]
Hi,

While I've successfully installed (and removed) tightvncserver as I am trying to get this ready for minecraft at school, I'm having trouble installing the VNC server on my Pi 3.  

pi@raspberrypi:~/.vnc $ curl -OL https://github.com/RealVNC/raspi-preview/releases/download/5.3.1.18206/VNC-Server-5.3.1-raspi-alpha1.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   610    0   610    0     0   4510      0 --:--:-- --:--:-- --:--:--  4552
 59  9.9M   59 6101k    0     0  1600k      0  0:00:06  0:00:03  0:00:03 1632kcurl: (23) **Failed writing body (453 != 1024)**

Thanks for your help.

**Comment by Mike-TB** [comment]
Ok, When in doubt, reboot. It's working now.

**Comment by sconemad** [comment]
Hi,

You should be aware that the version of VNC Server on this repo is an alpha version that we made available for people to try out prior to the official release. This has actually now been released, and is available to download from our website here: https://www.realvnc.com/docs/raspberry-pi.html

Or, if you have the latest version of Raspbian Pixel, it is included by default, and the VNC Server can be enabled via the Raspberry Pi configuration app (or raspi-config on the command line).

Sorry for the confusion.

**Comment by sconemad** [comment]
I've added a note to the README for this repo pointing to the stable version on our website.
